title: Operating Systems Coursework Journal
description: CMPN202 â€“ BSc Software Engineering | University of Roehampton

student:
  name: Azeez Jibola Akindele
  student_id: 23597614
  course: BSc Software Engineering
  module: Operating Systems

theme: jekyll-theme-minimal
